# Generated by Django 3.0.8 on 2021-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('alternativa1', models.CharField(max_length=255)),
                ('alternativa2', models.CharField(max_length=255)),
                ('alternativa3', models.CharField(max_length=255)),
                ('alternativa4', models.CharField(max_length=255)),
                ('resposta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
