# Generated by Django 3.2.5 on 2021-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210705_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='opiniao',
            field=models.TextField(default=''),
        ),
    ]
